Formatter config support
software-mansion/cairols pull request #128
Opened 2024-12-20 14:48 UTC by Draggu

Closes #56

---

**Stack**:
- #128 ⬅
- #127
- #126
- #125
- #124

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2025-01-07 10:51 UTC, piotmag769 approved these changes

2025-01-08 16:59 UTC, mkaput requested changes

2025-01-08 16:59 UTC, mkaput commented on src/project/manifest_registry/mod.rs
> +            manifest_dir.pop(); // Remove Scarb.toml from path
maybe add an assertion using https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.ends_with here?

2025-01-08 16:59 UTC, mkaput commented on src/ide/formatter.rs
> +    let path = file_uri.path();
you should rather use https://docs.rs/url/latest/url/struct.Url.html#method.to_file_path here

2025-01-08 16:59 UTC, mkaput commented on src/project/manifest_registry/mod.rs
> +    pub fn config_for_file(&self, path: &str) -> Option<MemberConfig> {
```suggestion
    pub fn config_for_file(&self, path: &Path) -> Option<MemberConfig> {
```

2025-01-09 10:48 UTC, Draggu commented on src/project/manifest_registry/member_config.rs
> +    fn fmt(pkg: &PackageMetadata) -> FormatterConfig {
Disagree, I want to make it like this in future

```rs
Self { 
    fmt: Self::fmt(pkg),
    lint: Self::lint(pkg),
    other_tool: Self::other_tool(pkg),
}
```

2025-01-10 09:16 UTC, mkaput approved these changes

2025-01-10 10:26 UTC, merged