Notify about invalid `cairo_project.toml`
software-mansion/cairols pull request #3
Opened 2024-11-29 05:04 UTC by piotmag769

2024-11-29 08:02 UTC, mkaput requested changes

2024-11-29 08:02 UTC, mkaput commented on src/lsp/ext.rs
> +}
```suggestion
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectConfigParsingFailedParams {
    pub project_config_path: String,
}
```

2024-11-29 08:02 UTC, mkaput commented on src/project/mod.rs
> +                                project_config_path: format!("{}", config_path.display()),
```suggestion
                                project_config_path: config_path.to_string.lossy().into(),
```

2024-12-02 07:20 UTC, mkaput approved these changes

2024-12-02 11:35 UTC, Draggu approved these changes

2024-12-02 15:20 UTC, merged