Make updating diagnostics atomic
software-mansion/cairols pull request #36
Opened 2024-12-11 18:12 UTC by piotmag769

2024-12-11 18:21 UTC, Draggu requested changes

2024-12-12 08:18 UTC, piotmag769 commented on src/lang/diagnostics/file_diagnostics.rs
>      pub parser: Diagnostics<ParserDiagnostic>,
Good point, missed it

2024-12-12 10:30 UTC, Draggu approved these changes

2024-12-12 11:23 UTC, mkaput approved these changes

2024-12-12 13:15 UTC, merged