Restart proc macro server on `Scarb.toml` change
software-mansion/cairols pull request #9
Opened 2024-12-02 11:00 UTC by Draggu

2024-12-02 11:33 UTC, piotmag769 approved these changes

2024-12-02 11:33 UTC, piotmag769 commented on src/lang/proc_macros/controller.rs
> +        db.cancel_all();
Smart

2024-12-03 13:37 UTC, mkaput requested changes

2024-12-03 13:37 UTC, mkaput commented on src/lang/proc_macros/controller.rs
> +    pub fn force_restart(&mut self, db: &mut AnalysisDatabase, config: &Config) {
doc

2024-12-03 13:49 UTC, mkaput requested changes

2024-12-03 13:49 UTC, mkaput commented on src/lang/proc_macros/controller.rs
> +    /// This ensures that a fresh proc-macro-server is used.
```suggestion
    /// Forcibly restarts the proc-macro-server, shutting down any currently running instances.
    ///
    /// A new server instance is only started if there are available restart attempts left.
    /// This ensures that a fresh proc-macro-server is used.
```

2024-12-04 11:13 UTC, merged